matrix:
  rows: 64
  cols: 64
  chain: 3
  brightness: 4
clock:
  font: fonts-aux/hoog36.bdf
  color: [255, 255, 50]
  format: "%H:%M"
  position: [67, 0]
sensors:
  font: fonts/6x13B.bdf
  position: [0, 0]

# color settings for each sensor type
  hdc1080: [0, 255, 0]
  bmp280: [0, 0, 255]
  bh1750: [0, 255, 255]
  mh-z19: [255, 255, 0]